name: Mirror Repository

on:
  push:
    branches: 
      - '*'  # Зеркалировать все ветки
    tags:
      - '*'  # Зеркалировать все теги

jobs:
  mirror:
    runs-on: ubuntu-cloud-runner
    permissions:
      contents: write  # Требуется для force push

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полная история коммитов

    - name: Configure Git
      run: |
        git config --global user.name "Alexey Ponikarov"
        git config --global user.email "ponikz@yandex.ru"

    - name: Mirror to Remote
      env:
        TARGET_REPO: "https://${{ secrets.GH_MIRROR_ACTOR }}:${{ secrets.MIRROR_TOKEN }}@github.com/ponikz/mirror_repo"
      run: |
        # Добавляем целевой репозиторий как remote
        git remote add target $TARGET_REPO
        
        # Синхронизируем все ветки и теги
        git push --mirror --force target
        
        # Альтернатива для конкретной ветки:
        # git push --force target HEAD:main